//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizTalkComponents.ExtensionObjects.DBLookupHelper.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BizTalkComponents.ExtensionObjects.DBLookupHelper.UnitTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set identity_insert customers on
        ///INSERT INTO [dbo].[Customers]
        ///		([CustomerId], [CustomerName],[Email],[Phone],[Address],[City],[ZipCode],[LastUpdate],[Comment])
        ///     VALUES
        ///		(&apos;1&apos;,&apos;John Smith&apos;,&apos;john.smith@somewhere.com&apos;,&apos;&apos;,&apos;&apos;,&apos;NewYork&apos;,&apos;&apos;,&apos;2019-02-27T13:45:02&apos;,&apos;customer updated &amp; verified&apos;),
        ///(&apos;2&apos;,&apos;Sara Konor&apos;,&apos;sara.konor@terminator.com&apos;,&apos;0123456&apos;,&apos;Top street&apos;,&apos;Dallas&apos;,&apos;123 45&apos;,&apos;2020-12-22T17:40:15&apos;,&apos;Top street
        ///Dallas123 45&apos;),
        ///(&apos;3&apos;,&apos;Anders Andersson&apos;,&apos;anders.andersson@here.se&apos;,&apos;34561&apos;,&apos;&apos;,&apos;NewYork&apos;,&apos;5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddRecords {
            get {
                return ResourceManager.GetString("AddRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///if exists(select 1 from sys.databases where name=&apos;Sales&apos;)
        ///drop database Sales
        ///
        ///create database Sales.
        /// </summary>
        internal static string Create_TestDatabase {
            get {
                return ResourceManager.GetString("Create_TestDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Customers](
        ///	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
        ///	[CustomerName] [nvarchar](50) NOT NULL,
        ///	[Email] [nvarchar](50) NULL,
        ///	[Phone] [nvarchar](50) NULL,
        ///	[Address] [nvarchar](50) NULL,
        ///	[City] [nvarchar](50) NULL,
        ///	[ZipCode] [nvarchar](50) NULL,
        ///	[LastUpdate] [datetime2](7) NULL,
        ///	[Comment] [nvarchar](200) NULL,
        ///PRIMARY KEY CLUSTERED 
        ///(
        ///	[CustomerId] ASC
        ///)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
    }
}
